// Mocks generated by Mockito 5.4.6 from annotations
// in shorten_my_link/test/cubit/home_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i4;
import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shorten_my_link/models/link_model.dart' as _i7;
import 'package:shorten_my_link/repositories/storage_repository.dart' as _i3;
import 'package:shorten_my_link/services/api_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStorageRepository_1 extends _i1.SmartFake
    implements _i3.StorageRepository {
  _FakeStorageRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i5.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_0(this, Invocation.getter(#dio)),
          )
          as _i2.Dio);

  @override
  _i3.StorageRepository get storageRepository =>
      (super.noSuchMethod(
            Invocation.getter(#storageRepository),
            returnValue: _FakeStorageRepository_1(
              this,
              Invocation.getter(#storageRepository),
            ),
          )
          as _i3.StorageRepository);

  @override
  _i6.Future<_i4.Either<String, String>> getLink(String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#getLink, [alias]),
            returnValue: _i6.Future<_i4.Either<String, String>>.value(
              _FakeEither_2<String, String>(
                this,
                Invocation.method(#getLink, [alias]),
              ),
            ),
          )
          as _i6.Future<_i4.Either<String, String>>);

  @override
  _i6.Future<_i4.Either<String, _i7.AliasModel>> registerShortLink(
    String? link,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#registerShortLink, [link]),
            returnValue: _i6.Future<_i4.Either<String, _i7.AliasModel>>.value(
              _FakeEither_2<String, _i7.AliasModel>(
                this,
                Invocation.method(#registerShortLink, [link]),
              ),
            ),
          )
          as _i6.Future<_i4.Either<String, _i7.AliasModel>>);

  @override
  List<_i7.AliasModel> getLinks() =>
      (super.noSuchMethod(
            Invocation.method(#getLinks, []),
            returnValue: <_i7.AliasModel>[],
          )
          as List<_i7.AliasModel>);

  @override
  void deleteLink(_i7.AliasModel? aliasModel) => super.noSuchMethod(
    Invocation.method(#deleteLink, [aliasModel]),
    returnValueForMissingStub: null,
  );
}
